# Generated by Django 4.1.1 on 2022-10-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_rename_preparación_receta_preparacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
    ]
