# Generated by Django 4.1.1 on 2022-10-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_rename_fotos_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='id',
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.FileField(upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
