# Generated by Django 4.1.1 on 2022-11-24 17:32

from django.db import migrations, models
import recetas.models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_remove_ingrediente_id_alter_foto_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=200, validators=[recetas.models.first_letter_capital]),
        ),
    ]
